apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: microservice-inventory
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_URL
          value: "mongodb://mongodb:27017"
        - name: ORDER_URL
          value: "http://order:4001/order"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: microservice-order
        imagePullPolicy: Never
        ports:
        - containerPort: 4001
        env:
        - name: MONGODB_URL
          value: "mongodb://mongodb:27017"
        - name: PRODUCT_URL
          value: "http://inventory:4000/product"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: microservice-user
        imagePullPolicy: Never
        ports:
        - containerPort: 4002
        env:
        - name: MONGODB_URL
          value: "mongodb://mongodb:27017"
        - name: ORDER_URL
          value: "http://order:4001/order"
        - name: PRODUCT_URL
          value: "http://order:4000/product"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}